### PR TITLE
Give opt out for the page angularJS check

### PR DESCRIPTION
**Pull request by lewisdawson15**
Some pages in my application aren't written in angularJS (specifically, the login page because of the way cookies are implemented). Can we give the option to opt out of this check? Is the code change sufficient to do so?

### CODE REVIEW

**Comment by kpodl** [comment]
Thanks for the patch and apologies for my delay in commenting on it!
This is something I wanted to have, as well.

Please take a look at the comments I made. After you have made the changes, I will merge the pull request and write a test for it.

**Comment by bootstraponline** [comment]
In protractor this is done by setting `browser.ignoreSynchronization = true`

**Comment by lewisdawson15** [comment]
Sorry I moved projects and forgot to finish this off. Should be okay now! :)

**Comment by bootstraponline** [comment]
I think the whole approach is incorrect though (at least if the idea is to match protractor.js).

**Comment by kpodl** [comment]
Thanks for your efforts @lewisdawson15. However, I have decided to go with introducing `ignore_synchronization` as a driver attribute. This is the same behavior as protractor uses and makes for cleaner code. v0.1.0 has the new updates.

**Pull request closed without merging**
