### PR TITLE
python3 compatibility

### PR DESCRIPTION
**Pull request by mwalkowski**
Please check it again and let me know

### CODE REVIEW

**Comment by jimfulton** [comment]
This depends on the ``future`` package. You need to include it in ``install_requires`` in in ``setup.py``

    install_requires=[
        'selenium>=2.47.3', 'future'
    ],

With this change, tests pass for me in Python 2.7 and 3.4.

**Comment by mwalkowski** [comment]
If you want I can update my PR.
3 lis 2015 15:02 "Jim Fulton" <notifications@github.com> napisał(a):

**Comment by jimfulton** [comment]
That would be a good idea.  I'm just an interested 3rd party. The more complete the PR is, the more likely @kpodl will be to accept it. :)

Thanks for creating this PR.

**Comment by mwalkowski** [comment]
done :)

**Comment by kpodl** [comment]
@mwalkowski Thanks a lot for the python 3 support! I feel very guilty for having included it yet, but I did not have the time. I have started reviewing the PR and I hope to integrate it this evening.
@jimfulton Thanks for the fix.

**Comment by kpodl** [comment]
PR has been merged. New release will follow shortly.

**Comment by jimfulton** [comment]
Any update on the release?

**Comment by jimfulton** [comment]
Thanks for making the release!

**Comment by kpodl** [comment]
You're welcome!

**Pull request merged**
